### ISSUE TITLE
#11 As a user I want to see which cards I have on my hand at all times.

### ISSUE THREAD

**Issue by LexHeggli** [sopra-fs21-group-22/client#11]
Acceptance Criteria: 

- [x] All the cards in my hand should be shown at the bottom beneath my user icon.
- [x] The cards should be able to be placed on the discard pile if I choose to do so and if  it’s my turn

⏰ Time estimate: 4h

**Comment by maettuu** [comment]
the front-end implementation is missing the connection to the back-end
