### ISSUE TITLE
#16  As a User I want to be able to play again after a finished game in order not to  search for another game lobby. 

### ISSUE THREAD

**Issue by LexHeggli** [sopra-fs21-group-22/client#16]
Acceptance Criteria: 

- [ ] A prompt should appear which asks the user whether he*she wants to play another game in the current game lobby. 
- [ ] The prompt should redirect the user to the main menu if he*she doesn’t want to play again. 

⏰ Time estimate: 1h

**Comment by maettuu** [comment]
possible to leave game and join new lobby
