### ISSUE TITLE
Playing Field: Circular view

### ISSUE THREAD

**Issue by LexHeggli** [sopra-fs21-group-22/client#45]
- [x] The user should see themselves at the bottom of the field and all the other players in  a circle in an aerial view 
- [x] There should be a resign button
- [x] There should be a end turn button
- [x] There should be an info button with the rules of the game

⏰ Time estimate: 3h
📌 This task is part of the user story #3.

**Comment by maettuu** [comment]
the front-end implementation is missing the connection to the back-end
