### ISSUE TITLE
Playing Field: Info about each player

### ISSUE THREAD

**Issue by LexHeggli** [sopra-fs21-group-22/client#46]
- [x] Each player should have a little profile icon
- [x] Each player should have a placeholder for blue cards
- [x] Each player should have a place for their life bullets
- [x] Each player should have a place for their hand cards (so the user can see the amount of hand cards each player has)

⏰ Time estimate: 3h
📌 This task is part of the user story #3 .

**Comment by maettuu** [comment]
the front-end implementation is missing the connection to the back-end
